### PR TITLE
Update SNESDev.c

### PR DESCRIPTION
**Pull request by 5StringsOfDoom**
Changed the BTN to MODE as TR2 was no longer responding, will also operate as the hotkey button on the Monster Joysticks arcade kit.

### CODE REVIEW

**Comment by 5StringsOfDoom** [comment]
Can this update please be merged with the master release?

**Comment by 5StringsOfDoom** [comment]
Thanks.

**Comment by petrockblog** [comment]
Thanks for the information about the unresponsive button. I hope that does not break something for other users :-)

**Comment by 5StringsOfDoom** [comment]
It's strange as it was working before the latest release of the RetroPie iso, so i moved it over to the MODE button and that seems to have fixed it. This makes more sense as you can assign this additional button the the Hotkey in emulation station. 

It shouldn't break anything for previous setups as it is just tapped onto the 13th bit of the shift register and the SNES controller only every used 12 of the 16bits available.

**Pull request merged**
